[package]
name = "hydractify"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.41.1", features = ["full"] }
