name: "Package the project's Linux binary"

on:
  push:
    branches:
      - 'main'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Building package
        id: build
        run: nix build 

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: hydractify-linux-unknown
          path: result/bin/hydractify
